name: GitHub Actions Test
on: [push]
jobs:
  Build-Cabal-Arm:
    name: Build armv7/aarch64 (Cabal)
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      TEST: "v1.0.0/main"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Create directory
        run: mkdir result
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          source: ".github/workflows/files/*"
          target: "github-test"
          strip_components: 3
      - name: Execute Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          envs: GITHUB_SHA,SHA
          script: |
            sh github-test/test1.sh "$GITHUB_SHA" "$SHA" "$TEST"
            sh test2.sh
      - name: Download files from remote server
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          insecure_ignore_fingerprint: true
          source: "github-test/test1.sh"
          target: "test1.sh"
      - name: Test downloaded file from remote server
        run: cat test1.sh
      - name: Remove files from server
        uses: appleboy/ssh-action@master
        if: always()
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          envs: GITHUB_SHA,SHA
          script: rm -rf ~/github-test
