name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
    Build-Windows-Cabal:
      name: Build Windows (Cabal)
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: haskell/actions/setup@v2
          id: windows-haskell-setup
          with:
            ghc-version: '8.10.7'
            cabal-version: '3.6.0.0'
        - name: Check installation
          run: cabal --version && ghc --version
        - uses: actions/cache@v3
          name: Cache cabal files
          with:
            path: |
              ${{ steps.windows-haskell-setup.outputs.cabal-store }}
              dist-newstyle
            key: ${{ runner.os }}-${{ hashFiles('simpleapp.cabal') }}
        - name: Run the app
          run: runhaskell app\Main.hs
        - name: Update, build and get the binary path
          id: windows-build
          run: |
            cabal v2-update
            cabal v2-build
            echo "::set-output name=binpath::$(cabal exec which simpleapp)"
        - name: Move the binary
          run: mkdir result && mv ${{ steps.windows-build.outputs.binpath }} result/simpleapp.exe
        - name: Upload binary
          uses: actions/upload-artifact@v3
          with:
            name: simpleapp
            path: simpleapp.exe
            if-no-files-found: error
