name: GitHub Actions Test
on: [push]
jobs:
  Copy-To-Remote:
    name: Copy to remote server
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
      TEST: "v1.0.0/main"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Create directory
        run: mkdir result
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_ARM_FINGERPRINT }}
          source: ".github/workflows/files/*"
          target: "github-test"
          strip_components: 3
      - name: Execute Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_ARM_FINGERPRINT }}
          envs: GITHUB_SHA,SHA
          script: |
            sh github-test/test1.sh "$GITHUB_SHA" "$SHA" "$TEST"
            sh github-test/test2.sh

  Copy-From-Remote:
    name: Copy from remote server
    needs: Copy-To-Remote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Download files from remote server
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_ARM_FINGERPRINT }}
          source: "github-test/test1.sh"
          target: "test1.sh"
      - name: Test downloaded file from remote server
        run: cat test1.sh

  Clean-Remote:
    name: Remove copied files from server
    needs: Copy-From-Remote
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Remove files from server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_ARM_FINGERPRINT }}
          envs: GITHUB_SHA,SHA
          script: rm -rf ~/github-test
