name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
    Build-Windows-Cabal:
      name: Build Windows (Cabal)
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: haskell/actions/setup@v2
          id: windows-haskell-cabal
          with:
            ghc-version: '8.10.7'
            cabal-version: '3.6.0.0'
        - name: Check installation
          run: cabal --version && ghc --version
        - uses: actions/cache@v3
          name: Cache cabal files
          with:
            path: |
              ${{ steps.windows-haskell-cabal.outputs.cabal-store }}
              dist-newstyle
            key: ${{ runner.os }}-${{ hashFiles('simpleapp.cabal') }}
        - name: Run the app
          run: runhaskell app\Main.hs
        - name: Update cabal package database
          run: cabal v2-update
        - name: Build the app
          run: cabal v2-build
        - name: Test local
          run: dir ~
        - name: Check where the binary is built
          id: windows-binary
          run: echo "::set-output name=path::$(cabal exec which simpleapp)"
        - name: Upload binary
          uses: actions/upload-artifact@v3
          with:
            name: simpleapp
            path: ${{ steps.windows-binary.outputs.path }}
            if-no-files-found: error
