name: GitHub Actions Test
on: [push]
jobs:
  Build-Cabal-Arm:
    name: Build armv7/aarch64 (Cabal)
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          source: ".github/workflows/files/*.sh"
          target: "github-test"
          strip_components: 3
      - name: Execute Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          script_stop: true
          envs: GITHUB_SHA,SHA
          script: |
            sh github-test/test1.sh && sh github-test/test2.sh
            echo $GITHUB_SHA
            echo $SHA
            rm -rf ~/github-test
