name: GitHub Actions Test
on: [push]
jobs:
  Copy-From-Remote:
    name: Copy from remote server
    needs: Copy-To-Remote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: mkdir result
      - name: Download files from remote server
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.SSH_ARM_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_ARM_PRIVATE_KEY }}
          fingerprint: ${{ secrets.SSH_ARM_FINGERPRINT }}
          source: "result/text1.txt"
          target: "result/text1.txt"
      - name: Test downloaded file from remote server
        run: |
          cat result/text1.txt
